name: deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: "12.x" #change this version if you want
  FLUTTER_VERSION: "2.2.3" #set here your version
  FLUTTER_CHANNEL: "stable" #set here your channel

jobs:
  build_web:
    name: Build for WEB
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          flutter pub get
          flutter build web
  publish_ghPages:
    name: Publish GH Pages
    needs: [build_web] #only trigger this, if the build_web job runs ok...
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          flutter pub get
          flutter build web --release
          cd build/web
          git init
          git config --global user.email den_spb97@mail.ru #change to your e-mail
          git config --global user.name dessy4oko #change to your user-name
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/dessy4oko/model_sys.git #change to your path
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
